### ISSUE TITLE
InventoryClickEvent error

### ISSUE THREAD

**Issue by Trippyn** [einTosti/BuildSystem#4]
**Describe the bug**
InventoryClikEvent error

**Screenshots**
`[13:14:24] [Server thread/ERROR]: Could not pass event InventoryClickEvent to BuildSystem v2.14.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[server.jar:git-Spigot-57bbdd8-dea4138]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Spigot-57bbdd8-dea4138]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[server.jar:git-Spigot-57bbdd8-dea4138]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[server.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2186) ~[server.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[server.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[server.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[server.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[server.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[server.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[server.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[server.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[server.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[server.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[server.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[server.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-57bbdd8-dea4138]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NoSuchMethodError: net.wesjd.anvilgui.AnvilGUI$Builder.item(Lorg/bukkit/inventory/ItemStack;)Lnet/wesjd/anvilgui/AnvilGUI$Builder;
        at de.eintosti.buildsystem.manager.WorldManager.openWorldAnvil(WorldManager.java:88) ~[?:?]
        at de.eintosti.buildsystem.listener.InventoryClickListener.onCreateInventoryClick(InventoryClickListener.java:314) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[server.jar:git-Spigot-57bbdd8-dea4138]
        ... 18 more`

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: Iphone X
 - OS: IOS 14.1
 - Browser Safari

**Bug**
If i open menu /worlds and I want to create world (empty, flat, etc...) it gives me the error.
I have latest version of the plugin v2.14.3
I have laters spigot version 1.16.3 
![image](https://user-images.githubusercontent.com/68424737/97886348-cbcc6700-1d28-11eb-9e56-83d00232c717.png)

**Comment by einTosti** [comment]
Should be fixed the lastest update (v2.14.4)
