### ISSUE TITLE
Error when creating a world with custom world gen.

### ISSUE THREAD

**Issue by EinJOJO** [einTosti/BuildSystem#71]
Logs.
```
BauServer_1.18.*-1][17:33:42 WARN]: [BuildSystem] Task #7991 for BuildSystem v2.17.1 generated an exception

[BauServer_1.18.*-1]java.lang.UnsupportedOperationException: null

[BauServer_1.18.*-1] at java.util.AbstractList.add(AbstractList.java:153) ~[?:?]

[BauServer_1.18.*-1] at java.util.AbstractList.add(AbstractList.java:111) ~[?:?]

[BauServer_1.18.*-1] at com.eintosti.buildsystem.manager.WorldManager.lambda$createCustomWorld$2(WorldManager.java:174) ~[buildsystem-2.17.1.jar:?]

[BauServer_1.18.*-1] at com.eintosti.buildsystem.util.external.PlayerChatInput.lambda$onPlayerChat$0(PlayerChatInput.java:87) ~[buildsystem-2.17.1.jar:?]

[BauServer_1.18.*-1] at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-101]

[BauServer_1.18.*-1] at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-101]

[BauServer_1.18.*-1] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-101]

[BauServer_1.18.*-1] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-101]

[BauServer_1.18.*-1] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-101]

[BauServer_1.18.*-1] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-101]

[BauServer_1.18.*-1] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-101]

[BauServer_1.18.*-1] at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

How: Create a world with custom world generation. 
Version: Paper 1.18.1 (101)

Trying to fix.

**Comment by EinJOJO** [comment]
Cannot replicate it on localhost ;-;

**Comment by EinJOJO** [comment]
btw. update your discord link.
Lost my old account 😢

**Comment by einTosti** [comment]
> btw. update your discord link.
> Lost my old account 😢

Yeah I kind of fucked up my website, will try and fix that soonish
For the meantime: https://discord.gg/ZCqbwajME6

**Comment by einTosti** [comment]
Btw, 2.18 is the newest version
